#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#By Amar Jasarbasic

def is_even(n):
    if n%2 == 0:
        return True
    else:
        return False

#recusrive funtion to gen fib numbers
def fib_num(n):
    if n == 1:
        return 1
    elif n == 2:
        return 1            
    else:
        return fib_num(n-1) + fib_num(n-2)

total = 0
n = 0
i = 1

while n <= 4000000:
    if is_even(fib_num(i)):
        total += fib_num(i)
    n = fib_num(i)
    i+=1

print (total)
